---
title: "POPI Disclaimer, Terms of Use and Privacy Policy"
---

## POPI Disclaimer

By accessing and viewing this website, or registering as a member, you hereby acknowledge that you have read and understand the Protection of Personal Information (POPI) disclaimer. SASA shall take all reasonable measures to protect the Personal Information of Data Subjects in our care.

For the purpose of this disclaimer "Personal Information" shall be defined as detailed in the Promotion of Access to Information Act 2 of 2000 ("PAIA") and the Protection of Personal Information Act 4 of 2013 ("POPI"). The PAIA and POPI Acts are available online at [www.gov.za/documents/acts](http://www.gov.za/documents/acts).

According to these definitions, personal information refers to information that relates specifically to information that can identify a living person, such as name, age, gender, identity number, email address etc.

SASA may collect, store and use your information primarily for the following purposes:

- To provide services to you as instructed and requested by you
- To compile non-personal statistical information about browsing habits, click patterns and access to this website

Whenever you use our website, complete an application form, contact us electronically or use one of the services offered by us, we will collect your personal information. The information we maintain concerning our clients is treated as confidential and protected with the necessary safety measures.

Should you have any queries relating to our compliance with the above mentioned legislation kindly contact our Information Officer at [info@sastat.org](mailto:info@sastat.org).

## How we use cookies

A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.

We use traffic log cookies to identify which pages are being used. This helps us analyse data about webpage traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.

Overall, cookies help us provide you with a better website by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.

You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.

## Links to other websites

Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.

## Privacy Policy (Member Data)

Member information is managed by a third party, namely Glue Up. Please view the Glue Up [terms and conditions](https://www.glueup.com/legal/user-agreement) and [privacy policy](https://www.glueup.com/legal/privacy-policy) for more information on how member data is stored and used.

### What we do with the member information provided

- We require this information to understand your needs and provide you with a better service, and in particular for SASA membership purposes.
- Internal record keeping.
- We may use the information to improve our services.
- We may periodically send emails about industry news, updates, or other information which we think you may find interesting using the email address which you have provided.
- From time to time, we may also use your information to contact you for market research purposes. We may contact you by email, phone, fax or mail. We may use the information to customise the website according to your interests.

### Controlling member personal information

Should you wish to deactivate your account, please email the [secretary](mailto:secretary@sastat.org) to notify us of this, and we will deactivate your account, and remove all your personal data.

We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so. We may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen.

You may request details of personal information which we hold about you. Please email the [secretary](mailto:secretary@sastat.org) should you wish to receive these details.

If you believe that any information we are holding on you is incorrect or incomplete, please write to or [email us](mailto:secretary@sastat.org) as soon as possible at the above address. We will promptly correct any information found to be incorrect. You can also update your member information using the [Glue Up service and platform](https://app.glueup.com/org/sastat/memberships).
