---
title: "Archive"
---

Older news items and event announcements, kept for reference.

## Stats@UP Research Reinforcement Day

*6 October 2021*

The Department of Statistics at the University of Pretoria is hosting a "Summer School" which is free to attend. The speakers are Prof Olcay Arslan, Prof Arthur Pewsey and Prof Antonio Punzo.

## Virtual seminar hosted by ICCSSA on 15 September 2021

*10 September 2021*

15 September 2021, virtual conference.

- 14:00 – 14:30. Presenter: Diego Iturralde (Statistics South Africa). Title: Application of the Alkire-Foster method to produce Covid-19 vulnerability and vaccination indices.
- 14:30 – 15:30. Presenters: Dr Jabu Mtsweni & Dr Ridhwaan Suliman (CSIR). Title: Data-driven decision making for government socio-economic interventions.

[Seminar invitation (PDF)](https://drive.google.com/a/sastat.org/open?id=120UO5sIeDGAy5Sxy2INmHvA2aznal4mU)

## Sub-Saharan Africa Network (SUSAN) 2021 Conference

*1 July 2021*

Sub-Saharan Africa Network (SUSAN) 2021 Conference, 6 – 9 September 2021, virtual conference, Kenya. Topic: "Biometry in the era of big data for health and food security". [Register here](https://www.susan2021.ibskenya.org/register).

## Early Career & Student Statisticians Conference (ECSSC) 2021

*10 June 2021*

The Statistical Society of Australia (SSA) will host the Early Career & Student Statisticians Conference (ECSSC) 2021 virtually from July 26th to August 1st 2021. ECSSC is a biennial conference for students and early career researchers in statistics aimed at developing, maintaining and improving contact and support amongst ECSSs working in various scientific disciplines, including agriculture, economics, bioinformatics, artificial intelligence and machine learning, and environmental statistics.

With ECSSC being held virtually for the first time, we thought that we would reach out beyond our own borders and see if there is perhaps interest from future budding statisticians in the region. ECSSC even offers a day for high school students and registration for high school students is free! The fees for everyone else are still competitive.

Online registration and information on the conference, keynote speakers, workshops, and abstract submissions are available at [http://ecssc2021.com.au/](http://ecssc2021.com.au/).

## Seminar at the Department of Statistics, the University of Pretoria

*7 June 2021*

You are invited to a seminar at the Department of Statistics, the University of Pretoria on Tuesday 8 June 10:30 – 11:30.

**Title:** Clustering via semi-parametric density estimation with skew-symmetric kernels<br>
**Authors:** Mahdi Salehi, Andriette Bekker, and Mohammad Arashi

**Abstract:** The idea behind density-based clustering is to associate groups to the connected components of the level sets of the density of the data to be estimated by a nonparametric method. This approach claims some advantages over both distance- and model-based clustering. Some researchers developed this technique by proposing a graph theory-based method for identifying local modes of the underlying density being estimated by the well-known kernel density estimation with normal kernels. The present work aims at improving the performance of the density-based clustering by using semi-parametric KDE with more flexible family of kernels belonging to skew-symmetric distributions. Finding optimum bandwidth under the mentioned kernels is another main topic of this presentation. Finally, some illustrative examples follow.

## Modelling Vaccine Rollout: Seminar hosted by ICCSSA

*29 April 2021, 14:00 – 16:30, Zoom*

**Speaker 1: Dr Ali Asgary (York University).** Mass Vaccination Options: simulation experiences of drive-thru and walk-in mass vaccination clinics.

Different mass vaccination options are available that can be used to vaccinate millions of people in a short period of time. Each option has its own pros and cons and various environmental, public health, and logistical factors and challenges need to be considered in their site selection, layout, staffing, resourcing and operations. Temporary drive-through and walk-in clinics are being proposed and used for mass vaccination during the covid-19 pandemic. In this presentation, these options are discussed and some of the simulations and applications developed at York University's Advanced Disaster, Emergency and Rapid-response Simulation (ADERSIM) to examine the effectiveness of these options with reference to some real world cases are examined.

Dr Ali Asgary is an associate professor and founding member of York University's Disaster and Emergency Management Program. Since 2015 he has been the associate director of the Advanced Disaster, Emergency and Rapid-response Simulation (ADERSIM) at York University. Dr Asgary's teaching and research interests are in diverse areas of disaster and emergency management with special focus on disaster and emergency simulation and modelling and business continuity, disaster recovery. He is currently involved as the principal investigator and co-investigator of a number of major research projects related to the COVID-19 pandemic funded by Canadian funding agencies including SSHRC, CIHR, NSERC, and DRDC, IDRC among others. He leads the ADERSIM mass vaccination simulation team at York University.

**Speaker 2: Prof Bruce Mellado (University of the Witwatersrand).** Modelling the vaccination roll out.

In this presentation, work in partnership with the Gauteng Department of Health in the area of vaccine roll out modelling will be summarised. This includes understanding target populations in light of different kinds of vulnerabilities. The use of Artificial Intelligence in this space will be showcased.

A PhD from Columbia University, Bruce Mellado is a Full Professor at the University of the Witwatersrand, a Senior Researcher of iThemba LABS and serves as the Director of the Institute for Collider Particle Physics. Prof Mellado is the National Contact Physicist of South Africa at the ATLAS experiment at CERN and is the co-Chair of the Nuclear Particle and Radiation Division of South African Institute of Physics. He is the recipient of several awards and fellowships. Prof Mellado is an internationally acclaimed, B1 rated researcher of the National Research Foundation of South Africa. He is an expert on the Higgs boson and was a leading participant in its discovery that was announced in 2012 and led to the Nobel Prize in Physics being awarded in 2013 to François Englert and Peter W. Higgs. He is a member of the Gauteng Premier's COVID-19 Advisory Committee, where he leads work on predictions, and is also the Co-President of the Africa-Canada Artificial Intelligence Data Modelling Consortium.

## "Under Lockdown" Photo Competition

*19 April 2021*

We have all, in some way or another, been affected by the COVID-19 pandemic and have had to adjust to a new "normal". From university staff and students to working professionals, we have all had to adjust to remote and online environments, all under varying circumstances and resources.

With this in mind, SASA asked its members to share their best (or worst) picture of working or studying "Under Lockdown". The winning entry was Aluwani Ramalata, who won a R500 Takealot voucher. We asked Aluwani to share the story behind the photo with SASA members.

Aluwani writes:

> "I graduated with an MSc (Statistics) from the University of Limpopo in 2017. Like many other students, I was looking forward to register for my PhD. Accordingly, I spent the whole of 2018 trying to identify both an area of interest and a supervisor. I ultimately identified Survival Analysis as my area of interest given that it is not yet much explored as we have few people in South Africa interested in that very area. Likewise, I spent the whole year of 2019 trying to browse through and casually review literature on the field of Survival Analysis. As life would have it, the Covid 19 pandemic set in and consequently its concomitant lockdown was declared at a time when I was in the process of formal registrations. Formal registration being put on hold, a team of my supervisors encouraged me to continue to intensify literature review irrespective of pending formal registration.
>
> Given their encouragement, I tried to read for the first two to three weeks, with no success due to the hectic schedule on the home front. If there is one thing that lockdown did not prepare me for, along with a million other women out there, is to be a nanny, maid, mother, wife, primary school teacher, lecturer and scholar at the same time. Being a mother to a toddler for whom five seconds of no supervision meant a lot of things can go wrong, I had to unfortunately put a freeze on most of my plans; robust scholarly engagement being one of those plans. Juggling a myriad of equally important activities at a time became the order of the day.
>
> At one point, I found myself attending a virtual meeting, while helping my other two kids with their school work which was due in the next 30 minutes or so, whilst holding my little screaming son on my lap. In the midst of all that hype, unexpectedly my Head of Department would unintentionally embarrassingly ask: "Mrs Ramalata what is your take on the matter?" At that very time, the funny or rather sad part was that I had no idea what was being discussed, owing to my momentary attention lapse. Finding myself cornered, I had to fall back on what African elders would normally do when caught off guard, I went: "Ke laka leo!" meaning, "I support what the previous speaker had said." Of course, that confidently said whilst covertly apprehensive, lest my retort is found irrelevant. Such were funny moments of my virtual meetings.
>
> However, I equally discovered fun moments when virtual teaching from home accidentally became my most favourite exploration. Although initially very tricky, the Blackboard Collaborate Ultra subsequently gave me an excitingly euphoric sense of face-to-face interaction. Every time before class time commenced, I had to make sure that my son went on an unscheduled sleep as classes were at different times on different days. It was during such moments that at times my attention-demanding son would wake up before my class finishes and then the surreptitious juggling gimmicks would begin. Honestly, though peppered with hilarious moments, it has not been an easy journey at all.
>
> With lockdown restrictions since relaxed, I am now able to go to the controlled environment of my office to attend virtual meetings and also teach from there. These have been personally stretching moments demanding witty adaptation and discovery of one's latent talents, patience and unexplored sides of self. The sad truth is, now with the world gone topsy-turvy, the new normal is not normal for all different individuals globally, and unless you are in their shoes, their situation will never make sense to you."

## International Statistical Institute (ISI) Online Short Courses Programme: 6 May – 1 July 2021

*9 April 2021*

Following the tradition of the previous years, the ISI held its 2021 edition of the Short Courses prior to the biennial ISI World Statistics Congress. The courses were scheduled from 6 May – 1 July 2021 in 3 hour sessions each day from 14.00-17.00 CEST. The programme was organized in cooperation with the ISI Associations and covered a wide range of topics from the areas of statistics and data science, including large-scale spatial data science, quality of multisource statistics, fraud analytics, financial accounts, technical editing and science communication, graph sampling, competing risks, recurrent event analysis in R, spatial statistical learning, tidyverse graphics, the statistical theory of deep learning, statistical disclosure control, machine learning, data science and predictive analytics, bootstrap methods and permutation tests, basketball data analysis, teaching data science, communicating health data, precision medicine and cure models.

Details: [https://www.isi-web.org/events/courses/short-2021](https://www.isi-web.org/events/courses/short-2021)

## SASA Registration now OPEN!

*9 April 2021*

SASA is in the process of making some changes to modernise our association and bring additional benefits to our members. As part of this, we have partnered with a new platform, Glue Up, to manage memberships. It is envisaged that through this platform we will be able to engage with you, as a member, more meaningfully and provide you with a more rewarding SASA experience. We as a society are excited to reach out to our members, and broader statistics community. Watch out for announcements for exciting events coming your way.

[Watch the introduction video](https://www.youtube.com/watch?v=TOiV4XXGtO4)
